### PR TITLE
[RM Ch 3] Energy efficiency opportunities

### PR DESCRIPTION
**Pull request by walterkozlowski**
partially addresses Issue https://github.com/anuket-project/anuket-specifications/issues/3419
This is the first of several PRs to come related to this issue

### CODE REVIEW

**Comment by CsatariGergely** [comment]
There are some hickups in the bullet list formatting. If that is okay for you I can push a commit to fix them. 

Could be great, thanks.  The issue is that I cannot preview the files, for some reasons. We need to fix this, as basically we have to write in dark...

**Comment by walterkozlowski** [comment]
@CsatariGergely, Preview seem to be working for all chapters except Chapter 3.  So this is not an issue with this PR but with Chapter 3.  Maybe because it is much bigger than other chapters? Any idea?

**Review by Bharath-KKB — APPROVED** [review]
Might make sense to move this change to the beginning of energy efficiency (line 1963)

In the next PR I will add more information and re-think how to perhaps re-order.  Thanks for suggestion.

**Review by petorre — APPROVED** [review]

**Review by bfcohen100 — COMMENTED** [review]
Not sure why I cannot approve this.  I have two accounts and I think the approval goes with the other account.

**Review by bfcohen — COMMENTED** [review]
Looks ok as a start.

**Pull request merged**
